---
# Inventario de Ansible para Executive Service Business
all:
  children:
    esb_vms:
      hosts:
        esb-vm:
          ansible_host: 143.47.38.168
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/oracle_key
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

      vars:
        # Configuración de dominios
        corporativa_domain: executiveservicebusiness.duckdns.org
        eyenga_domain: eyenga.duckdns.org

        # Configuración DuckDNS
        duckdns_domains:
          - name: executiveservicebusiness
            token: "a7c4d0ad-114e-40ef-ba1d-d217904a50f2"
          - name: eyenga
            token: "a7c4d0ad-114e-40ef-ba1d-d217904a50f2"

        # Configuración de aplicaciones
        app_user: ubuntu
        app_directory: /home/ubuntu/executiveservicebusiness-web
        web_root: /var/www

        # Configuración Git
        git_repo: https://github.com/CSalamanca/executiveservicebusiness-web.git
        git_branch: oracle-vm

        # Configuración Nginx
        nginx_sites_available: /etc/nginx/sites-available
        nginx_sites_enabled: /etc/nginx/sites-enabled

        # SSL/TLS
        enable_ssl: true
        letsencrypt_email: admin@executiveservicebusiness.duckdns.org
