---
# Inventario de Ansible para Executive Service Business
all:
  children:
    esb_vms:
      hosts:
        esb-vm:
          ansible_host: 141.253.199.218
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/oracle_key
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

      vars:
        # Configuración de dominios
        corporativa_domain: executiveservicebusiness.duckdns.org
        eyenga_domain: eyenga.duckdns.org

        # Configuración DuckDNS
        duckdns_domains:
          - name: executiveservicebusiness
            token: "ab030fef-94f3-4234-a8a1-b1b6fe69de8e"
          - name: eyenga
            token: "ab030fef-94f3-4234-a8a1-b1b6fe69de8e"

        # Configuración DuckDNS adicional
        duckdns_update_interval: 30 # minutos
        duckdns_log_file: /var/log/duckdns.log
        log_rotation_days: 7
        log_rotation_size: 10M

        # Configuración de aplicaciones
        app_user: ubuntu
        app_directory: /home/ubuntu/executiveservicebusiness-web
        web_root: /var/www

        # Configuración Git
        git_repo: https://github.com/CSalamanca/executiveservicebusiness-web.git
        git_branch: oracle-vm

        # Configuración Nginx
        nginx_sites_available: /etc/nginx/sites-available
        nginx_sites_enabled: /etc/nginx/sites-enabled
        nginx_client_max_body_size: 16M

        # SSL/TLS
        enable_ssl: true
        letsencrypt_email: admin@executiveservicebusiness.duckdns.org

        # Configuración de firewall - Solo puertos 22 y 443 (configuración final)
        firewall_rules:
          - { rule: allow, port: 22, proto: tcp, comment: "SSH access" }
          - { rule: allow, port: 443, proto: tcp, comment: "HTTPS access" }
