---
# Handlers para Nginx

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  become: yes

- name: test nginx
  command: nginx -t
  become: yes
  changed_when: false
